[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "zlib", "ffmpeg", "glib", "libGL", "libSM", "libXext", "libXrender"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
