"""Shared failure-reason strings used by validators and the renderer.

Importing constants (instead of hardcoding strings in two places) prevents
drift between what `story_validators` emits and what the renderer's
manifest writes / what acceptance tests grep for.
"""

# Global truth gate
BALL_TOO_FAR_FROM_CARRIER       = "BALL_TOO_FAR_FROM_CARRIER"
BALL_NOT_VISIBLE                = "BALL_NOT_VISIBLE"
LOW_HOMOGRAPHY_CONFIDENCE       = "LOW_HOMOGRAPHY_CONFIDENCE"
TRACK_ID_UNSTABLE               = "TRACK_ID_UNSTABLE"
LOW_CARRIER_CONFIDENCE          = "LOW_CARRIER_CONFIDENCE"

# Pressing triangle
TRIANGLE_TOO_LARGE              = "TRIANGLE_TOO_LARGE"
NO_REAL_COVER_DEFENDER          = "NO_REAL_COVER_DEFENDER"
PRESSER_TOO_FAR                 = "PRESSER_TOO_FAR"
CARRIER_OUTSIDE_TRIANGLE        = "CARRIER_OUTSIDE_TRIANGLE"
DEFENDERS_COLLINEAR             = "DEFENDERS_COLLINEAR"

# Pressing trap
INSUFFICIENT_DEFENDERS_FOR_TRAP = "INSUFFICIENT_DEFENDERS_FOR_TRAP"
ESCAPE_ANGLE_TOO_LARGE          = "ESCAPE_ANGLE_TOO_LARGE"
NO_DIRECTIONAL_FORCE            = "NO_DIRECTIONAL_FORCE"

# Passing-lane / 1v1
PASSING_LANE_NOT_ACTUALLY_BLOCKED = "PASSING_LANE_NOT_ACTUALLY_BLOCKED"
SECOND_DEFENDER_PRESENT         = "SECOND_DEFENDER_PRESENT"
DEFENDER_NOT_ENGAGING           = "DEFENDER_NOT_ENGAGING"

# Recovery run
RUN_NOT_TOWARD_OWN_GOAL         = "RUN_NOT_TOWARD_OWN_GOAL"
SPEED_TOO_LOW                   = "SPEED_TOO_LOW"
NO_TRANSITION_THREAT            = "NO_TRANSITION_THREAT"

ALL_REASONS = (
    BALL_TOO_FAR_FROM_CARRIER, BALL_NOT_VISIBLE, LOW_HOMOGRAPHY_CONFIDENCE,
    TRACK_ID_UNSTABLE, LOW_CARRIER_CONFIDENCE,
    TRIANGLE_TOO_LARGE, NO_REAL_COVER_DEFENDER, PRESSER_TOO_FAR,
    CARRIER_OUTSIDE_TRIANGLE, DEFENDERS_COLLINEAR,
    INSUFFICIENT_DEFENDERS_FOR_TRAP, ESCAPE_ANGLE_TOO_LARGE, NO_DIRECTIONAL_FORCE,
    PASSING_LANE_NOT_ACTUALLY_BLOCKED, SECOND_DEFENDER_PRESENT,
    DEFENDER_NOT_ENGAGING,
    RUN_NOT_TOWARD_OWN_GOAL, SPEED_TOO_LOW, NO_TRANSITION_THREAT,
)
